name: test

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: rust:1.74
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --verbose
